### ISSUE TITLE
npm 安装失败

### ISSUE THREAD

**Issue by mrossZ** [windy-boy/vue-car-number#1]
rror: EPERM: operation not permitted, unlink 'C:\zw\joven\gitlab\WX-LGXS-F\node_modules\core-js\modules'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\zw\joven\gitlab\WX-LGXS-F\node_modules\core-js\modules'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\zw\joven\gitlab\WX-LGXS-F\node_modules\core-js\modules'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\zw\\joven\\gitlab\\WX-LGXS-F\\node_modules\\core-js\\modules'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'C:\\zw\\joven\\gitlab\\WX-LGXS-F\\node_modules\\core-js\\modules'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\zw\\joven\\gitlab\\WX-LGXS-F\\node_modules\\core-js\\modules',
npm ERR!   parent: 'WX-LGXS-F'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zw\AppData\Roaming\npm-cache\_logs\2020-12-15T08_44_28_700Z-debug.log

**Comment by windy-boy** [comment]
当前环境其他的插件可以安装吗？看报错信息是npm没有权限操作安装目录。可以新建个项目重新安装看下。

**Comment by windy-boy** [comment]
还有问题吗？没有的话就关闭该issue了，后续有问题再提issue。
